sudo: required
services:
        - docker
before_install:
        - docker build -t aliavci/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true aliavci/react-test npm run test -- --coverage

after_success:
        - docker build -t aliavci/multi-client ./client
        - docker build -t aliavci/multi-nginx ./nginx
        - docker build -t aliavci/multi-server ./server
        - docker build -t aliavci/multi-worker ./worker
        - echo "$DO_PASS" | docker login -u "$DO_ID" --password-stdin
        - docker push aliavci/multi-client
        - docker push aliavci/multi-nginx
        - docker push aliavci/multi-server
        - docker push aliavci/multi-worker
deploy:
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-065246796665
        bucket_path: multi-docker
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
